<?php
/**
 * DispositivoApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Practica 2
 *
 * Especificación de los distintos servicios para la Práctica 2
 *
 * OpenAPI spec version: 1.0.0
 * Contact: rmg150@gcloud.ua.es
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.33
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use Swagger\Client\Api\DispositivoApi;
use Swagger\Client\Configuration;
use Swagger\Client\ApiException;
use Swagger\Client\ObjectSerializer;
use Webmozart\Assert\Assert;

/**
 * DispositivoApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class DispositivoApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for borrarDispositivo
     *
     * Borra el dispositivo.
     *
     */
    public function testBorrarDispositivo()
    {
    }

    /**
     * Test case for consultarDispositivo
     *
     * obtiene el dispositivo a partir de su codigo.
     *
     */
    public function testConsultarDispositivo()
    {
        $codigo = 70;
        $api = new DispositivoApi();

        $resultado = $api->consultarDispositivo($codigo, "consultarDispositiv");
        $this->assertSame(70, $resultado->getCodigo());
        $this->assertSame("Insertado", $resultado->getDescripcion());
    }

    /**
     * Test case for modificarDispositivo
     *
     * Modifica la sala.
     *
     */
    public function testModificarDispositivo()
    {
    }

    /**
     * Test case for nuevoDispositivo
     *
     * Crear un nuevo dispositivo.
     *
     */
    public function testNuevoDispositivo()
    {
    }
}
