<?php
/**
 * NivelApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Practica 2
 *
 * Especificación de los distintos servicios para la Práctica 2
 *
 * OpenAPI spec version: 1.0.0
 * Contact: rmg150@gcloud.ua.es
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.33
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use Swagger\Client\Configuration;
use Swagger\Client\ApiException;
use Swagger\Client\ObjectSerializer;

/**
 * NivelApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class NivelApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for borrarNivel
     *
     * Borra el {id} del nivel.
     *
     */
    public function testBorrarNivel()
    {
    }

    /**
     * Test case for consultarNivel
     *
     * obtiene todos los datos del {nivel} especificado.
     *
     */
    public function testConsultarNivel()
    {
    }

    /**
     * Test case for modificarNivel
     *
     * Modificar {id} del nivel.
     *
     */
    public function testModificarNivel()
    {
    }

    /**
     * Test case for nuevoNivel
     *
     * Crear un nuevo nivel.
     *
     */
    public function testNuevoNivel()
    {
    }
}
