<?php
/**
 * SalaApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Practica 2
 *
 * Especificación de los distintos servicios para la Práctica 2
 *
 * OpenAPI spec version: 1.0.0
 * Contact: rmg150@gcloud.ua.es
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.33
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use Swagger\Client\Configuration;
use Swagger\Client\ApiException;
use Swagger\Client\ObjectSerializer;

/**
 * SalaApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class SalaApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for borrarSala
     *
     * Borra {id} de la sala.
     *
     */
    public function testBorrarSala()
    {
    }

    /**
     * Test case for consultarSala
     *
     * obtiene el {id} de la sala de la BBDD.
     *
     */
    public function testConsultarSala()
    {
    }

    /**
     * Test case for modificarSala
     *
     * Modificar {id} de la sala.
     *
     */
    public function testModificarSala()
    {
    }

    /**
     * Test case for nuevaSala
     *
     * Crear una nueva sala.
     *
     */
    public function testNuevaSala()
    {
    }
}
